name: 'release'
on:
  push:
    tags:
      - 'v*'

# Don't cancel in progress since we don't want to have half-baked release.
concurrency: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-release'

jobs:
  # ci:
  #   uses: 'abcxyz/access-on-demand/.github/workflows/ci.yml@main' # ratchet:exclude

  github-release:
    # Run CI before the release
    # needs: ['ci']
    runs-on: 'ubuntu-latest'
    environment: release
    permissions:
      contents: 'write'
      packages: 'write'
    steps:
      - uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f' # ratchet:actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: 'goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757' # ratchet:goreleaser/goreleaser-action@v3
        with:
          version: 'v1.16.1' # Manually pinned
          args: 'release --clean'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
