name: 'reusable_create_tag'
on:
  workflow_call:
    inputs:
      tag:
        description: 'The name of the tag to be created.'
        type: 'string'
        required: true
      branch:
        description: 'The branch to create tag from.'
        type: 'string'
        required: false
        default: 'main'
      message:
        description: 'Message for the tag.'
        type: 'string'
        required: false
      env:
        type: 'string'
        required: true

jobs:
  create-tag:
    runs-on: 'ubuntu-latest'
    environment: '${{ inputs.env }}'
    permissions:
      contents: 'write'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: 'create tag'
        uses: 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' # ratchet:actions/github-script@v6
        with:
          # Use token minter access token.
          github-token: '${{ github.token }}'
          retries: '3'
          script: |+
            await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ inputs.tag }}',
              object: '${{ github.sha }}',
              type: 'commit',
              message: '${{ inputs.message }}'
            });

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.tag}}',
              sha: '${{ github.sha }}',
            })
