name: 'reusable_create_tag'
on:
  workflow_call:
    inputs:
      tag:
        description: 'The name of the tag to be created.'
        type: 'string'
        required: true
      annotated_tag:
        description: 'Create an annotated tag in Git.'
        type: boolean
        default: true
        required: false
      branch:
        description: 'The branch of the head commit to create tag on.'
        type: 'string'
        default: '${{ github.event.repository.default_branch }}'
        required: false
      message:
        description: 'Message for the tag.'
        type: 'string'
        default: '${{ inputs.tag }}'
        required: false
      env:
        type: 'string'
        required: true

jobs:
  create-tag:
    runs-on: 'ubuntu-latest'
    if: '${{ github.ref_name == github.event.repository.default_branch }}'
    environment: '${{ inputs.env }}'
    permissions:
      contents: 'write'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: 'create tag'
        uses: 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' # ratchet:actions/github-script@v6
        env:
          BRANCH: '${{ inputs.branch }}'
          TAG: '${{ inputs.tag }}'
          ANNOTATED_TAG: '${{ inputs.annotated_tag }}'
          MESSAGE: '${{ inputs.message }}'
        with:
          github-token: '${{ github.token }}'
          retries: '3'
          script: |+
            const branch = process.env.BRANCH
            const tag = process.env.TAG
            const message = process.env.MESSAGE
            const annotatedTag = process.env.ANNOTATED_TAG

            // TODO(#215): Once prevent self-review in supported by GitHub, we can remove this condition.
            if (branch != '${{ github.event.repository.default_branch }}') {
              core.info(`Skip creating tag as currently we only support creating tags on repository default branch`)
              return
            }

            let sha = '${{ github.sha }}'
            if (branch !== '${{ github.ref_name }}') {
              core.info(`get branch (${{ github.ref_name }})`)
              // Get branch.
              const branchToTag = await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
              })
              // Branch returns the latest commit info. See schema:
              // https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#get-a-branch
              sha = branchToTag['data']['commit']['sha']
            } else {
              core.info('skipped get branch')
            }

            await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag,
              object: sha,
              type: 'commit',
              message: message,
            });

            if (annotatedTag === 'true') {
              // Create a reference for annotated tag. See reference:
              // https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#create-a-tag-object
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tag}`,
                sha: sha,
              })
              core.info(`Created annotated tag (${tag}), branch (${branch}), commit (${sha}).`)
            } else {
              core.info(`Created lightweight tag (${tag}), branch (${branch}), commit (${sha}).`)
            }
